import React, { useState } from 'react';
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

const ReportForm = () => {
  const [startDate, setStartDate] = useState(new Date());
  const [input, setInput] = useState({
    reportgenerated: "",
    date: "",
    month: "",
    qc_status: "",
  });

  const [error, setError] = useState({});

  const handleChange = (event) => {
    const { name, value } = event.target;
    setInput((prev) => ({
      ...prev, [name]: value,
    }));
  };

  const handleDateChange = (date) => {
    setStartDate(date);
    setInput((prev) => ({
      ...prev, date: date.toISOString().split('T')[0],
    }));
  };

  const Validate = () => {
    const newErrors = {};
    if (!input.reportgenerated) newErrors.reportgenerated = 'This is Required*';
    if (!input.date) newErrors.date = 'This is Required*';
    if (!input.month) newErrors.month = 'This is Required*';
    if (!input.qc_status) newErrors.qc_status = 'This is Required*';
    else { }
    return newErrors;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const validateError = Validate();
    if (Object.keys(validateError).length === 0) {

      setError({});
    } else {
      setError(validateError);
    }
  };

  const options = [
    { value: "MANJUNATH H S" },
    { value: "MUTHU K" },
    { value: "AARTI MOHAN" },
    { value: "PARIMALA" },
    { value: "RAMYA R" },
    { value: "PRADEEP KUMAR" },
    { value: "SOUJANYA" },
    { value: "JAYAKUMAR VELU" },
    { value: "RAJ KUMAR" },
    { value: "SHRUTI M" },
    { value: "AKSHATHA SHETTY" },
    { value: "CASE UPLOAD" },
    { value: "CHAKRAVARTHI K C" },
  ];

  return (
    <form onSubmit={handleSubmit} className='grid grid-cols-5 gap-3 px-3'>
      <div className="mb-4">
        <label htmlFor="reportGeneratedby">REPORT GENERATED BY</label>
        <select
          name="reportgenerated"
          id="reportGeneratedby"
          className="outline-none pe-14 ps-2 text-left rounded-md w-full border p-2 mt-2"
          onChange={handleChange}
          value={input.reportgenerated}
        >
          <option value="">Select an option</option>
          {options.map((curElm) => (
            <option key={curElm.value} value={curElm.value}>{curElm.value}</option>
          ))}
        </select>
        {error.reportgenerated && <p className='text-red-500'>{error.reportgenerated}</p>}
      </div>
      <div className="mb-4">
        <label htmlFor="date" className="block">Date</label>
        <DatePicker
          selected={startDate}
          onChange={handleDateChange}
          name='date'
          className="border w-full rounded-md p-2 mt-2"
        />
        {error.date && <p className='text-red-500'>{error.date}</p>}
      </div>
      <div className="mb-4">
        <label htmlFor="ReportGeneratedMonth">REPORT GENERATED BY MONTH</label>
        <select
          name="month"
          id="ReportGeneratedMonth"
          className="outline-none pe-14 ps-2 text-left rounded-md w-full border p-2 mt-2"
          onChange={handleChange}
          value={input.month}
        >
          <option value="">Select a month</option>
          <option value="Jan">Jan</option>
          <option value="Feb">Feb</option>
          <option value="Mar">Mar</option>
          <option value="Apr">Apr</option>
          <option value="May">May</option>
          <option value="Jun">Jun</option>
          <option value="Jul">Jul</option>
        </select>
        {error.month && <p className='text-red-500'>{error.month}</p>}
      </div>
      <div className="mb-4">
        <label htmlFor="QCStatus" className="block">QC STATUS FETCH</label>
        <select
          name="qc_status"
          id="QCStatus"
          className="outline-none pe-14 ps-2 text-left rounded-md w-full border p-2 mt-2"
          onChange={handleChange}
          value={input.qc_status}
        >
          <option value="">CHOOSE QC STATUS</option>
          <option value="QC STATUS FETCH YES">QC STATUS FETCH YES</option>
          <option value="QC STATUS FETCH NO">QC STATUS FETCH NO</option>
        </select>
        {error.qc_status && <p className='text-red-500'>{error.qc_status}</p>}
      </div>
      <div className="mb-4 flex items-end"> 
        <p></p> 
        <button className="bg-[#3e76a5] text-white w-full rounded-md p-3" type='submit'>Submit</button>
      </div>
    </form>
  );
}

export default ReportForm;
